#message:2F:(Game_Credits) {
	[Style inspect]
	Made by Wrymouth using Star Rod[BR]
	for decomp and papermario-dx,[BR]
	after searching the entire [BR]
	codebase to remove the things dx[BR]
	[Wait][Next]
	added that I didn't like.[BR]
	[BR]
	Star Rod made by clover,[BR]
	papermario-dx made by alex.[BR]
	[Wait][Next]
	Music imported by Wrymouth.[BR]
	Midi credits:[BR]
	-Dave Phaneuf[BR]
	-Monster Iestyn[BR]
	[Wait][Next]
	Sprite credits:[BR]
	[Wait][Next]
	-Superjustinbros[BR]
	-Skylights[BR]
	-A.J. Nitro[BR]
	-Sunny Cassette[Wait][End]
}

#message:2F:(Game_Intro) {
	[Style narrate]Welcome to the first edition of[BR]
	Retro Rumble![BR]
	[Wait][Next]
	Today, our contestant Mario will be[BR]
	facing off against some iconic[BR]
	figures![BR]
	[Wait][Next]
	Get ready, the first round starts[BR]
	now![Wait][End]
}

#message:2F:(Game_SonicIntro) {
	[Style narrate]What a fight![BR]
	[Pause 10]Our next contestant is...[BR]
	[Wait][Next]
	...Huh. This will be a decent bit[BR]
	tougher.[BR]
	You know what, we'll give Mario a[BR]
	hand here.[BR]
	[Wait][Next]
	He gets the Super Boots.[BR]
	He gets the Ultra Hammer, which[BR]
	deals 5 damage in one hit.[BR]
	[Wait][Next]
	He gets Multibounce.[BR]
	He gets Super Jump Charge.[BR]
	He gets Hammer Throw.[BR]
	He gets Power Smash.[BR]
	[Wait][Next]
	He gets two Happy Flowers.[BR]
	He gets Power Rush.[BR]
	He gets Damage Dodge.[BR]
	[Wait][Next]
	On top of all this, he gets a bunch[BR]
	of items as well![BR]
	[Wait][Next]
	Are you ready, Mario?[BR]
	Here comes the next challenger![Wait][End]
}

#message:2F:(Game_Goombario_Bowser_Tattle) {
	[Style right]It's Bowser! He looks a little[BR]
	different from how I remember[BR]
	him, though.[BR]
	[Wait][Next]
	Max HP: 99, Attack Power: 3[BR]
	Defense Power: 0[BR]
	I don't think we're equipped[BR]
	to deal with this...[Wait][End]
}

#message:2F:(Game_Goombario_Axe_Tattle) {
	[Style right]It's an axe. Maybe we can use it[BR]
	to destroy the bridge?[BR]
	[Wait][Next]
	Max HP: 3, Attack Power: 0[BR]
	Defense Power: 0[BR]
	Let's give it a shot, okay?[Wait][End]
}

#message:2F:(Game_Dialog_Bowser_Tattle) {
	[Style inspect]It's Bowser! He looks a little[BR]
	different from how I remember[BR]
	him, though.[BR]
	[Wait][Next]
	Max HP: 99, Attack Power: 3[BR]
	Defense Power: 0[BR]
	I don't think we're equipped[BR]
	to deal with this...[Wait][End]
}

#message:2F:(GameEnemies_Axe) {
	Axe[End]
}

#message:2F:(GameEnemies_Sonic) {
	Sonic[End]
}

#message:2F:(GameEnemies_Tails) {
	Tails[End]
}

#message:2F:(GameEnemies_Knuckles) {
	Knuckles[End]
}

#message:2F:(Game_Goombario_Sonic_Tattle) {
	[Style right]It's Sonic![BR]
	[Wait][Next]
	Max HP: 20, Attack Power: 3[BR]
	Defense Power: 0[BR]
	This guy looks fast![Wait][End]
}

#message:2F:(Game_Goombario_Tails_Tattle) {
	[Style right]It's Tails![BR]
	[Wait][Next]
	Max HP: 30, Attack Power: 3[BR]
	Defense Power: 0[BR]
	[Wait][Next]
	Those tails must be quite[BR]
	strong to hold his weight[BR]
	for so long...[Wait][End]
}

#message:2F:(Game_Goombario_Knuckles_Tattle) {
	[Style right]It's Knuckles![BR]
	[Wait][Next]
	Max HP: 20, Attack Power: 5[BR]
	Defense Power: 0[BR]
	This guy's quite strong![BR]
	Be careful, Mario![Wait][End]
}

#message:2F:(Game_YouWin) {
	[Style inspect]You win![Wait][End]
}

#message:0B:(CH0_00BA) {
	[Style right]You can do it, Mario![Wait][End]
}
