#message:2F:(Game_Credits) {
	[Style inspect]Made by Wrymouth[BR]
	[Wait][Next]
	Sprite credits:[BR]
	Superjustinbros[BR]
	Skylights[BR]
	[Wait][Next]
	A.J. Nitro[BR]
	Sunny Cassette[BR]
	[Wait][End]
}

#message:2F:(Game_Goombario_Bowser_Tattle) {
	[Style right]It's Bowser! He looks a little[BR]
	different from how I remember[BR]
	him, though.[BR]
	[Wait][Next]
	Max HP: 99, Attack Power: 3[BR]
	Defense Power: 0[BR]
	I don't think we're equipped[BR]
	to deal with this...[Wait][End]
}

#message:2F:(Game_Goombario_Axe_Tattle) {
	[Style right]It's an axe. Maybe we can use it[BR]
	to destroy the bridge?[BR]
	[Wait][Next]
	Max HP: 5, Attack Power: 0[BR]
	Defense Power: 0[BR]
	Let's give it a shot, okay?[Wait][End]
}

#message:2F:(Game_Dialog_Bowser_Tattle) {
	[Style inspect]It's Bowser! He looks a little[BR]
	different from how I remember[BR]
	him, though.[BR]
	[Wait][Next]
	Max HP: 99, Attack Power: 3[BR]
	Defense Power: 0[BR]
	I don't think we're equipped[BR]
	to deal with this...[Wait][End]
}

#message:2F:(GameEnemies_Axe) {
	Axe[End]
}

#message:2F:(GameEnemies_Sonic) {
	Sonic[End]
}

#message:2F:(GameEnemies_Tails) {
	Tails[End]
}

#message:2F:(GameEnemies_Knuckles) {
	Knuckles[End]
}

#message:2F:(Game_Goombario_Sonic_Tattle) {
	[Style right]It's Sonic![BR]
	[Wait][Next]
	Max HP: 20, Attack Power: 3[BR]
	Defense Power: 0[BR]
	This guy looks fast![Wait][End]
}

#message:2F:(Game_Goombario_Tails_Tattle) {
	[Style right]It's Tails![BR]
	[Wait][Next]
	Max HP: 30, Attack Power: 3[BR]
	Defense Power: 0[BR]
	[Wait][Next]
	Those tails must be quite[BR]
	strong to hold his weight[BR]
	for so long...[Wait][End]
}

#message:2F:(Game_Goombario_Knuckles_Tattle) {
	[Style right]It's Knuckles![BR]
	[Wait][Next]
	Max HP: 20, Attack Power: 5[BR]
	Defense Power: 0[BR]
	This guy's quite strong![BR]
	Be careful, Mario![Wait][End]
}

#message:2F:(Game_YouWin) {
	[Style inspect]You win![Wait][End]
}
