#message:2F:(Game_Credits) {
	[Style inspect]Made by Wrymouth[Wait][End]
}

#message:2F:(Game_Goombario_Bowser_Tattle) {
	[Style right]It's Bowser! He looks a little[BR]
	different from how I remember[BR]
	him, though.[BR]
	[Wait][Next]
	Max HP: 99, Attack Power: 3[BR]
	Defense Power: 0[BR]
	I don't think we're equipped[BR]
	to deal with this...[Wait][End]
}

#message:2F:(Game_Goombario_Axe_Tattle) {
	[Style right]It's an axe. Maybe we can use it[BR]
	to destroy the bridge?[BR]
	[Wait][Next]
	Max HP: 5, Attack Power: 0[BR]
	Defense Power: 0[BR]
	Let's give it a shot, okay?[Wait][End]
}

#message:2F:(Game_Dialog_Bowser_Tattle) {
	[Style inspect]It's Bowser! He looks a little[BR]
	different from how I remember[BR]
	him, though.[BR]
	[Wait][Next]
	Max HP: 99, Attack Power: 3[BR]
	Defense Power: 0[BR]
	I don't think we're equipped[BR]
	to deal with this...[Wait][End]
}

#message:2F:(GameEnemies_Axe) {
	Axe[End]
}
